export const PLAN_ARGS_PREVIEW_CHARS = 200;
export const CORRECTOR_REASON_PREVIEW_CHARS = 200;
export const CORRECTOR_ERROR_SNIPPET_CHARS = 500;
export const CORRECTOR_FILE_SNIPPET_CHARS = 8000;
export const CORRECTOR_FILE_READ_CAP_BYTES = 32 * 1024;
